hydra:
  run:
    dir: ${scene.out_path}

projectname: Gaussian_Splatting

scene:
  model_path: ""
  scene_color: [0, 0, 0]

  sh_degree: 3
  device: "cuda:0"

  saving_iterations: ${optim.saving_iterations}

  data:
    name: "lego"
    eval: false
    source_path: "data/nerf_synthetic/lego"

  out_path: outputs/${projectname}/${scene.data.name}/${now:%Y%m%d_%H%M%S}
  log_path: ${scene.out_path}/log

render:
  bg_color: ${scene.scene_color}
  sh_degree: ${scene.sh_degree}
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false


optim:
  iterations: 30_000
  saving_iterations: [10_000, 20_000, 30_000]

  lambda_dssim: 0.2

  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30_000
  
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.005
  rotation_lr: 0.001


policy:

  percent_dense: 0.01
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15_000
  densify_grad_threshold: 0.0002
  random_background: false


sys:
  dataCls: ""
  sceneCls: ""
  modelCls: ""
  policyCls: ""
  optimerCls: ""
  lossCls: ""
  renderCls: ""
